# Generated by Django 4.1.5 on 2023-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0072_safecontract_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safecontract',
            name='name',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
