# Generated by Django 4.2.4 on 2023-10-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0074_internaltx_history_internal_transfer_idx'),
        ('history', '0075_safecontract_archived'),
    ]

    operations = [
    ]
